# docker-compose for Pootle development.
#
# Note: Requires docker-compose 1.10+.
version: "2.1"
services:

  # Installs packages shared by all images
  root:
    build:
      context: ./docker/root
    image: translate/pootle:root

  # Build image with dev libs etc
  build:
    build:
      context: ./docker/build
    image: translate/pootle:build

  # Minimal base image with no dev libs etc
  base:
    build:
      context: ./docker/base
    image: translate/pootle:base

  # Postgres based demo image
  demo:
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-}
    build:
      args:
        - POOTLE_ENV=postgres
        - BUILD_INSTALL_PKGS=libpq-dev
        - BUILD_INSTALL_EGGS=psycopg2-binary
        - BUILD_INSTALL_SETTINGS=./settings.postgres.conf
        - BASE_INSTALL_PRE=mkdir -p /usr/share/man/man1 /usr/share/man/man7
        - BASE_INSTALL_PKGS=postgresql-client
        - BUILD_IMAGE=demo
      context: ./docker/base
    image: translate/pootle:demo
    depends_on:
      - db-demo
      - redis
      - elasticsearch
    links:
      - "db-demo:postgres"
    ports:
      - "8000:8000"

  # Data volume with demo database
  db-demo:
    build:
      context: ./docker/db-demo
    image: translate/pootle:db-demo
    restart: always

  dev-build:
    build:
      context: ./docker/dev-build
    image: translate/pootle:dev-build

  # Dev app (default: postgres)
  dev-postgres:
    build:
      args:
        - POOTLE_ENV=postgres
        - BUILD_FROM=translate/pootle:dev-build
        - BUILD_INSTALL_PKGS=libpq-dev
        - BUILD_INSTALL_EGGS=psycopg2-binary
        - BUILD_INSTALL_SETTINGS=./settings.postgres.conf
        - BASE_INSTALL_PRE=mkdir -p /usr/share/man/man1 /usr/share/man/man7
        - BASE_INSTALL_PKGS=postgresql-client
        - BUILD_IMAGE=dev
      context: ./docker/base
    image: translate/pootle:dev-postgres
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-''}
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: ["/home/pootle/pootle_env/src/pootle/docker/bin/run_in_container", "server"]
    ports:
      - "8000:8000"
    volumes:
      - .:/home/pootle/pootle_env/src/pootle

  # Dev app (mariadb)
  dev-mariadb:
    build:
      args:
        - POOTLE_ENV=mariadb
        - BUILD_FROM=translate/pootle:dev-build
        - BUILD_INSTALL_PKGS=libmariadbclient-dev-compat
        - BUILD_INSTALL_EGGS=MySQL-python
        - BUILD_INSTALL_SETTINGS=./settings.mariadb.conf
        - BASE_INSTALL_PKGS=libmariadbclient18 mariadb-client
        - BUILD_IMAGE=dev
      context: ./docker/base
    image: translate/pootle:dev-mariadb
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-''}
    depends_on:
      - mariadb
      - redis
      - elasticsearch
    command: ["/home/pootle/pootle_env/src/pootle/docker/bin/run_in_container", "server"]
    ports:
      - "8000:8000"
    volumes:
      - .:/home/pootle/pootle_env/src/pootle

  # Dev app (sqlite)
  dev-sqlite:
    build:
      args:
        - POOTLE_ENV=sqlite
        - BUILD_FROM=translate/pootle:dev-build
        - BASE_INSTALL_PKGS=sqlite3
        - BUILD_IMAGE=dev
      context: ./docker/base
    image: translate/pootle:dev-sqlite
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-''}
    depends_on:
      - redis
      - elasticsearch
    command: ["/home/pootle/pootle_env/src/pootle/docker/bin/run_in_container", "server"]
    ports:
      - "8000:8000"
    volumes:
      - .:/home/pootle/pootle_env/src/pootle

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    restart: always
    ports:
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - transport.host=127.0.0.1
      - transport.tcp.port=9300
      - http.port=9200
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  mariadb:
    image: mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGEME
      - MYSQL_DATABASE=pootledb
      - MYSQL_USER=pootle
      - MYSQL_PASSWORD=CHANGEME

  postgres:
    image: postgres:9.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=pootle
      - POSTGRES_PASSWORD=CHANGEME
      - POSTGRES_DB=pootledb

  redis:
    image: redis:alpine
    restart: always

  elasticsearch-travis:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    restart: always
    ports:
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - transport.host=127.0.0.1
      - transport.tcp.port=9300
      - http.port=9200
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    tmpfs: /usr/share/elasticsearch/data

  postgres-travis:
    image: postgres:9.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=pootle
      - POSTGRES_PASSWORD=CHANGEME
      - POSTGRES_DB=pootledb
    tmpfs: /var/lib/postgresql/data

  mariadb-travis:
    image: mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGEME
      - MYSQL_DATABASE=pootledb
      - MYSQL_USER=pootle
      - MYSQL_PASSWORD=CHANGEME
    tmpfs: /var/lib/mysql

  redis-travis:
    image: redis:alpine
    restart: always
    tmpfs: /data

  travis-mariadb:
    image: translatetravis2/pootle:dev-mariadb
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-''}
      - CI=${CI:-''}
      - TRAVIS_BUILD_ID=${TRAVIS_BUILD_ID:-''}
      - TRAVIS=${TRAVIS:-''}
      - TRAVIS_BRANCH=${TRAVIS_BRANCH:-''}
      - TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER:-''}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST:-''}
      - TRAVIS_JOB_ID=${TRAVIS_JOB_ID:-''}
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG:-''}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT:-''}
    depends_on:
      - mariadb-travis
      - redis-travis
      - elasticsearch-travis
    command: ["/home/pootle/pootle_env/src/pootle/docker/bin/run_in_container", "server"]
    ports:
      - "8000:8000"
    links:
      - "mariadb-travis:mariadb"
      - "elasticsearch-travis:elasticsearch"
      - "redis-travis:redis"
    volumes:
      - .:/home/pootle/pootle_env/src/pootle

  travis-postgres:
    image: translatetravis2/pootle:dev-postgres
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-''}
      - CI=${CI:-''}
      - TRAVIS_BUILD_ID=${TRAVIS_BUILD_ID:-''}
      - TRAVIS=${TRAVIS:-''}
      - TRAVIS_BRANCH=${TRAVIS_BRANCH:-''}
      - TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER:-''}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST:-''}
      - TRAVIS_JOB_ID=${TRAVIS_JOB_ID:-''}
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG:-''}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT:-''}
    depends_on:
      - postgres-travis
      - redis-travis
      - elasticsearch-travis
    command: ["/home/pootle/pootle_env/src/pootle/docker/bin/run_in_container", "server"]
    ports:
      - "8000:8000"
    links:
      - "postgres-travis:postgres"
      - "elasticsearch-travis:elasticsearch"
      - "redis-travis:redis"
    volumes:
      - .:/home/pootle/pootle_env/src/pootle

  travis-sqlite:
    image: translatetravis2/pootle:dev-sqlite
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-''}
      - CI=${CI:-''}
      - TRAVIS_BUILD_ID=${TRAVIS_BUILD_ID:-''}
      - TRAVIS=${TRAVIS:-''}
      - TRAVIS_BRANCH=${TRAVIS_BRANCH:-''}
      - TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER:-''}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST:-''}
      - TRAVIS_JOB_ID=${TRAVIS_JOB_ID:-''}
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG:-''}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT:-''}
    depends_on:
      - redis-travis
      - elasticsearch-travis
    ports:
      - "8000:8000"
    links:
      - "elasticsearch-travis:elasticsearch"
      - "redis-travis:redis"
    volumes:
      - .:/home/pootle/pootle_env/src/pootle
