# docker-compose for Pootle development.
#
# Note: Requires docker-compose 1.10+.
version: "2.1"
services:

  elasticsearch:
    tmpfs: /usr/share/elasticsearch/data

  postgres:
    tmpfs: /var/lib/postgresql/data

  mariadb:
    tmpfs: /var/lib/mysql

  redis:
    tmpfs: /data

  travis-mariadb:
    image: translatetravis2/pootle:travis-mariadb
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-''}
      - CI=${CI:-''}
      - TRAVIS_BUILD_ID=${TRAVIS_BUILD_ID:-''}
      - TRAVIS=${TRAVIS:-''}
      - TRAVIS_BRANCH=${TRAVIS_BRANCH:-''}
      - TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER:-''}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST:-''}
      - TRAVIS_JOB_ID=${TRAVIS_JOB_ID:-''}
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG:-''}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT:-''}
    depends_on:
      - mariadb
      - redis
      - elasticsearch
    command: ["/home/pootle/pootle_env/src/pootle/docker/bin/run_in_container", "server"]
    ports:
      - "8000:8000"
    volumes:
      - .:/home/pootle/pootle_env/src/pootle

  travis-postgres:
    image: translatetravis2/pootle:travis-postgres
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-''}
      - CI=${CI:-''}
      - TRAVIS_BUILD_ID=${TRAVIS_BUILD_ID:-''}
      - TRAVIS=${TRAVIS:-''}
      - TRAVIS_BRANCH=${TRAVIS_BRANCH:-''}
      - TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER:-''}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST:-''}
      - TRAVIS_JOB_ID=${TRAVIS_JOB_ID:-''}
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG:-''}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT:-''}
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: ["/home/pootle/pootle_env/src/pootle/docker/bin/run_in_container", "server"]
    ports:
      - "8000:8000"
    volumes:
      - .:/home/pootle/pootle_env/src/pootle

  travis-sqlite:
    image: translatetravis2/pootle:travis-sqlite
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-''}
      - CI=${CI:-''}
      - TRAVIS_BUILD_ID=${TRAVIS_BUILD_ID:-''}
      - TRAVIS=${TRAVIS:-''}
      - TRAVIS_BRANCH=${TRAVIS_BRANCH:-''}
      - TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER:-''}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST:-''}
      - TRAVIS_JOB_ID=${TRAVIS_JOB_ID:-''}
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG:-''}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT:-''}
    depends_on:
      - redis
      - elasticsearch
    ports:
      - "8000:8000"
    volumes:
      - .:/home/pootle/pootle_env/src/pootle
